[package]
name = "paloma-provider-anthropic"
version = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
license = { workspace = true }
publish = false

[dependencies]
async-trait = { workspace = true }
eventsource-stream = { workspace = true }
futures = { workspace = true }
log = { workspace = true }
oauth2 = { workspace = true }
paloma-provider-base = { workspace = true }
paloma-provider-protocol = { workspace = true }
paloma-utils = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["io-std", "macros", "rt-multi-thread"] }

[lints]
workspace = true
