[workspace]
resolver = "3"
members = ["core", "ffi", "gui/scry-gtk", "uniffi-bindgen"]

[workspace.package]
version = "0.0.1"
edition = "2024"
rust-version = "1.93.0"

[workspace.dependencies]
futures = "0.3.32"
log = "0.4.33"
serde_json = "1.0.150"
tokio = { version = "1.52.3", default-features = false }
uniffi = "0.32.0"
uuid = { version = "1.23.4", default-features = false }

[profile.release]
lto = "thin"
codegen-units = 1
strip = true
