[package]
name = "scry-provider-protocol"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
prost = "0.14.4"
serde = { workspace = true }
tokio-util = { workspace = true }

[build-dependencies]
prost-build = "0.14.4"
protoc-bin-vendored = "3.2.0"

[dev-dependencies]
serde_json = { workspace = true }
