[package]
name = "paloma-provider-protocol"
version = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
license = "Apache-2.0"
publish = false

[dependencies]
prost = { workspace = true }
serde = { workspace = true }

[build-dependencies]
prost-build = { workspace = true }
protoc-bin-vendored = { workspace = true }

[dev-dependencies]
paloma-utils = { workspace = true }
serde_json = { workspace = true }
tokio-util = { workspace = true }

[lints]
workspace = true
