[package]
name = "paloma-extension-protocol"
version = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
license = "Apache-2.0"
publish = false

[dependencies]
prost = { workspace = true }

[build-dependencies]
prost-build = { workspace = true }
protoc-bin-vendored = { workspace = true }

[lints]
workspace = true
