// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: schema/extension/capability.proto

package extensionv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Capability struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CapabilityId  string                 `protobuf:"bytes,1,opt,name=capability_id,json=capabilityId,proto3" json:"capability_id,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Search        *SearchFacet           `protobuf:"bytes,3,opt,name=search,proto3,oneof" json:"search,omitempty"`
	Tool          *ToolFacet             `protobuf:"bytes,4,opt,name=tool,proto3,oneof" json:"tool,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Capability) Reset() {
	*x = Capability{}
	mi := &file_schema_extension_capability_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Capability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Capability) ProtoMessage() {}

func (x *Capability) ProtoReflect() protoreflect.Message {
	mi := &file_schema_extension_capability_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Capability.ProtoReflect.Descriptor instead.
func (*Capability) Descriptor() ([]byte, []int) {
	return file_schema_extension_capability_proto_rawDescGZIP(), []int{0}
}

func (x *Capability) GetCapabilityId() string {
	if x != nil {
		return x.CapabilityId
	}
	return ""
}

func (x *Capability) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Capability) GetSearch() *SearchFacet {
	if x != nil {
		return x.Search
	}
	return nil
}

func (x *Capability) GetTool() *ToolFacet {
	if x != nil {
		return x.Tool
	}
	return nil
}

// placeholder to indicate capability has search support
type SearchFacet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchFacet) Reset() {
	*x = SearchFacet{}
	mi := &file_schema_extension_capability_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchFacet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchFacet) ProtoMessage() {}

func (x *SearchFacet) ProtoReflect() protoreflect.Message {
	mi := &file_schema_extension_capability_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchFacet.ProtoReflect.Descriptor instead.
func (*SearchFacet) Descriptor() ([]byte, []int) {
	return file_schema_extension_capability_proto_rawDescGZIP(), []int{1}
}

type CapabilityIcon struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Icon:
	//
	//	*CapabilityIcon_Name
	//	*CapabilityIcon_Path
	//	*CapabilityIcon_Embedded
	Icon          isCapabilityIcon_Icon `protobuf_oneof:"icon"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapabilityIcon) Reset() {
	*x = CapabilityIcon{}
	mi := &file_schema_extension_capability_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilityIcon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilityIcon) ProtoMessage() {}

func (x *CapabilityIcon) ProtoReflect() protoreflect.Message {
	mi := &file_schema_extension_capability_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilityIcon.ProtoReflect.Descriptor instead.
func (*CapabilityIcon) Descriptor() ([]byte, []int) {
	return file_schema_extension_capability_proto_rawDescGZIP(), []int{2}
}

func (x *CapabilityIcon) GetIcon() isCapabilityIcon_Icon {
	if x != nil {
		return x.Icon
	}
	return nil
}

func (x *CapabilityIcon) GetName() string {
	if x != nil {
		if x, ok := x.Icon.(*CapabilityIcon_Name); ok {
			return x.Name
		}
	}
	return ""
}

func (x *CapabilityIcon) GetPath() string {
	if x != nil {
		if x, ok := x.Icon.(*CapabilityIcon_Path); ok {
			return x.Path
		}
	}
	return ""
}

func (x *CapabilityIcon) GetEmbedded() []byte {
	if x != nil {
		if x, ok := x.Icon.(*CapabilityIcon_Embedded); ok {
			return x.Embedded
		}
	}
	return nil
}

type isCapabilityIcon_Icon interface {
	isCapabilityIcon_Icon()
}

type CapabilityIcon_Name struct {
	Name string `protobuf:"bytes,1,opt,name=name,proto3,oneof"`
}

type CapabilityIcon_Path struct {
	Path string `protobuf:"bytes,2,opt,name=path,proto3,oneof"`
}

type CapabilityIcon_Embedded struct {
	Embedded []byte `protobuf:"bytes,3,opt,name=embedded,proto3,oneof"`
}

func (*CapabilityIcon_Name) isCapabilityIcon_Icon() {}

func (*CapabilityIcon_Path) isCapabilityIcon_Icon() {}

func (*CapabilityIcon_Embedded) isCapabilityIcon_Icon() {}

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Input         string                 `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_schema_extension_capability_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_schema_extension_capability_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_schema_extension_capability_proto_rawDescGZIP(), []int{3}
}

func (x *SearchRequest) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Item                `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_schema_extension_capability_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_schema_extension_capability_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_schema_extension_capability_proto_rawDescGZIP(), []int{4}
}

func (x *SearchResponse) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Subtitle      *string                `protobuf:"bytes,2,opt,name=subtitle,proto3,oneof" json:"subtitle,omitempty"`
	Icon          *CapabilityIcon        `protobuf:"bytes,3,opt,name=icon,proto3,oneof" json:"icon,omitempty"`
	Actions       []*Action              `protobuf:"bytes,4,rep,name=actions,proto3" json:"actions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_schema_extension_capability_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_schema_extension_capability_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_schema_extension_capability_proto_rawDescGZIP(), []int{5}
}

func (x *Item) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Item) GetSubtitle() string {
	if x != nil && x.Subtitle != nil {
		return *x.Subtitle
	}
	return ""
}

func (x *Item) GetIcon() *CapabilityIcon {
	if x != nil {
		return x.Icon
	}
	return nil
}

func (x *Item) GetActions() []*Action {
	if x != nil {
		return x.Actions
	}
	return nil
}

type Action struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// action name for both UI display and as action enum
	Label string `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	// action input params
	Params []string `protobuf:"bytes,2,rep,name=params,proto3" json:"params,omitempty"`
	// whether the action is the default action
	Primary       bool `protobuf:"varint,3,opt,name=primary,proto3" json:"primary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Action) Reset() {
	*x = Action{}
	mi := &file_schema_extension_capability_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Action) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Action) ProtoMessage() {}

func (x *Action) ProtoReflect() protoreflect.Message {
	mi := &file_schema_extension_capability_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Action.ProtoReflect.Descriptor instead.
func (*Action) Descriptor() ([]byte, []int) {
	return file_schema_extension_capability_proto_rawDescGZIP(), []int{6}
}

func (x *Action) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *Action) GetParams() []string {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *Action) GetPrimary() bool {
	if x != nil {
		return x.Primary
	}
	return false
}

type RunActionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        *Action                `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunActionRequest) Reset() {
	*x = RunActionRequest{}
	mi := &file_schema_extension_capability_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunActionRequest) ProtoMessage() {}

func (x *RunActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_schema_extension_capability_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunActionRequest.ProtoReflect.Descriptor instead.
func (*RunActionRequest) Descriptor() ([]byte, []int) {
	return file_schema_extension_capability_proto_rawDescGZIP(), []int{7}
}

func (x *RunActionRequest) GetAction() *Action {
	if x != nil {
		return x.Action
	}
	return nil
}

type RunActionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Behavior:
	//
	//	*RunActionResponse_Hide
	//	*RunActionResponse_Stay
	//	*RunActionResponse_Replace
	Behavior      isRunActionResponse_Behavior `protobuf_oneof:"behavior"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunActionResponse) Reset() {
	*x = RunActionResponse{}
	mi := &file_schema_extension_capability_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunActionResponse) ProtoMessage() {}

func (x *RunActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_schema_extension_capability_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunActionResponse.ProtoReflect.Descriptor instead.
func (*RunActionResponse) Descriptor() ([]byte, []int) {
	return file_schema_extension_capability_proto_rawDescGZIP(), []int{8}
}

func (x *RunActionResponse) GetBehavior() isRunActionResponse_Behavior {
	if x != nil {
		return x.Behavior
	}
	return nil
}

func (x *RunActionResponse) GetHide() *Hide {
	if x != nil {
		if x, ok := x.Behavior.(*RunActionResponse_Hide); ok {
			return x.Hide
		}
	}
	return nil
}

func (x *RunActionResponse) GetStay() *Stay {
	if x != nil {
		if x, ok := x.Behavior.(*RunActionResponse_Stay); ok {
			return x.Stay
		}
	}
	return nil
}

func (x *RunActionResponse) GetReplace() *Replace {
	if x != nil {
		if x, ok := x.Behavior.(*RunActionResponse_Replace); ok {
			return x.Replace
		}
	}
	return nil
}

type isRunActionResponse_Behavior interface {
	isRunActionResponse_Behavior()
}

type RunActionResponse_Hide struct {
	Hide *Hide `protobuf:"bytes,1,opt,name=hide,proto3,oneof"`
}

type RunActionResponse_Stay struct {
	Stay *Stay `protobuf:"bytes,2,opt,name=stay,proto3,oneof"`
}

type RunActionResponse_Replace struct {
	Replace *Replace `protobuf:"bytes,3,opt,name=replace,proto3,oneof"`
}

func (*RunActionResponse_Hide) isRunActionResponse_Behavior() {}

func (*RunActionResponse_Stay) isRunActionResponse_Behavior() {}

func (*RunActionResponse_Replace) isRunActionResponse_Behavior() {}

type Hide struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hide) Reset() {
	*x = Hide{}
	mi := &file_schema_extension_capability_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hide) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hide) ProtoMessage() {}

func (x *Hide) ProtoReflect() protoreflect.Message {
	mi := &file_schema_extension_capability_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hide.ProtoReflect.Descriptor instead.
func (*Hide) Descriptor() ([]byte, []int) {
	return file_schema_extension_capability_proto_rawDescGZIP(), []int{9}
}

type Stay struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Stay) Reset() {
	*x = Stay{}
	mi := &file_schema_extension_capability_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stay) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stay) ProtoMessage() {}

func (x *Stay) ProtoReflect() protoreflect.Message {
	mi := &file_schema_extension_capability_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stay.ProtoReflect.Descriptor instead.
func (*Stay) Descriptor() ([]byte, []int) {
	return file_schema_extension_capability_proto_rawDescGZIP(), []int{10}
}

// replace the launcher input with the given text
type Replace struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Input         string                 `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Replace) Reset() {
	*x = Replace{}
	mi := &file_schema_extension_capability_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Replace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Replace) ProtoMessage() {}

func (x *Replace) ProtoReflect() protoreflect.Message {
	mi := &file_schema_extension_capability_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Replace.ProtoReflect.Descriptor instead.
func (*Replace) Descriptor() ([]byte, []int) {
	return file_schema_extension_capability_proto_rawDescGZIP(), []int{11}
}

func (x *Replace) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

// all unary request errors populate through this response
type ExtensionError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtensionError) Reset() {
	*x = ExtensionError{}
	mi := &file_schema_extension_capability_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtensionError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtensionError) ProtoMessage() {}

func (x *ExtensionError) ProtoReflect() protoreflect.Message {
	mi := &file_schema_extension_capability_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtensionError.ProtoReflect.Descriptor instead.
func (*ExtensionError) Descriptor() ([]byte, []int) {
	return file_schema_extension_capability_proto_rawDescGZIP(), []int{12}
}

func (x *ExtensionError) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_schema_extension_capability_proto protoreflect.FileDescriptor

const file_schema_extension_capability_proto_rawDesc = "" +
	"\n" +
	"!schema/extension/capability.proto\x12\x11paloma.extension.v1\x1a\x1bschema/extension/tool.proto\"\xdb\x01\n" +
	"\n" +
	"Capability\x12#\n" +
	"\rcapability_id\x18\x01 \x01(\tR\fcapabilityId\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12;\n" +
	"\x06search\x18\x03 \x01(\v2\x1e.paloma.extension.v1.SearchFacetH\x00R\x06search\x88\x01\x01\x125\n" +
	"\x04tool\x18\x04 \x01(\v2\x1c.paloma.extension.v1.ToolFacetH\x01R\x04tool\x88\x01\x01B\t\n" +
	"\a_searchB\a\n" +
	"\x05_tool\"\r\n" +
	"\vSearchFacet\"b\n" +
	"\x0eCapabilityIcon\x12\x14\n" +
	"\x04name\x18\x01 \x01(\tH\x00R\x04name\x12\x14\n" +
	"\x04path\x18\x02 \x01(\tH\x00R\x04path\x12\x1c\n" +
	"\bembedded\x18\x03 \x01(\fH\x00R\bembeddedB\x06\n" +
	"\x04icon\"%\n" +
	"\rSearchRequest\x12\x14\n" +
	"\x05input\x18\x01 \x01(\tR\x05input\"?\n" +
	"\x0eSearchResponse\x12-\n" +
	"\x05items\x18\x01 \x03(\v2\x17.paloma.extension.v1.ItemR\x05items\"\xc4\x01\n" +
	"\x04Item\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x1f\n" +
	"\bsubtitle\x18\x02 \x01(\tH\x00R\bsubtitle\x88\x01\x01\x12:\n" +
	"\x04icon\x18\x03 \x01(\v2!.paloma.extension.v1.CapabilityIconH\x01R\x04icon\x88\x01\x01\x123\n" +
	"\aactions\x18\x04 \x03(\v2\x19.paloma.extension.v1.ActionR\aactionsB\v\n" +
	"\t_subtitleB\a\n" +
	"\x05_icon\"P\n" +
	"\x06Action\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12\x16\n" +
	"\x06params\x18\x02 \x03(\tR\x06params\x12\x18\n" +
	"\aprimary\x18\x03 \x01(\bR\aprimary\"E\n" +
	"\x10RunActionRequest\x121\n" +
	"\x06action\x18\x01 \x01(\v2\x19.paloma.extension.v1.ActionR\x06action\"\xb5\x01\n" +
	"\x11RunActionResponse\x12-\n" +
	"\x04hide\x18\x01 \x01(\v2\x17.paloma.extension.v1.HideH\x00R\x04hide\x12-\n" +
	"\x04stay\x18\x02 \x01(\v2\x17.paloma.extension.v1.StayH\x00R\x04stay\x126\n" +
	"\areplace\x18\x03 \x01(\v2\x1a.paloma.extension.v1.ReplaceH\x00R\areplaceB\n" +
	"\n" +
	"\bbehavior\"\x06\n" +
	"\x04Hide\"\x06\n" +
	"\x04Stay\"\x1f\n" +
	"\aReplace\x12\x14\n" +
	"\x05input\x18\x01 \x01(\tR\x05input\"&\n" +
	"\x0eExtensionError\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05errorB\xd1\x01\n" +
	"\x15com.paloma.extension.v1B\x0fCapabilityProtoP\x01ZApaloma/extensions/webfetch/internal/pb/schema/extension;extensionv1\xa2\x02\x03SEX\xaa\x02\x11Paloma.Extension.V1\xca\x02\x11Paloma\\Extension\\V1\xe2\x02\x1dPaloma\\Extension\\V1\\GPBMetadata\xea\x02\x13Paloma::Extension::V1b\x06proto3"

var (
	file_schema_extension_capability_proto_rawDescOnce sync.Once
	file_schema_extension_capability_proto_rawDescData []byte
)

func file_schema_extension_capability_proto_rawDescGZIP() []byte {
	file_schema_extension_capability_proto_rawDescOnce.Do(func() {
		file_schema_extension_capability_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_schema_extension_capability_proto_rawDesc), len(file_schema_extension_capability_proto_rawDesc)))
	})
	return file_schema_extension_capability_proto_rawDescData
}

var file_schema_extension_capability_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_schema_extension_capability_proto_goTypes = []any{
	(*Capability)(nil),        // 0: paloma.extension.v1.Capability
	(*SearchFacet)(nil),       // 1: paloma.extension.v1.SearchFacet
	(*CapabilityIcon)(nil),    // 2: paloma.extension.v1.CapabilityIcon
	(*SearchRequest)(nil),     // 3: paloma.extension.v1.SearchRequest
	(*SearchResponse)(nil),    // 4: paloma.extension.v1.SearchResponse
	(*Item)(nil),              // 5: paloma.extension.v1.Item
	(*Action)(nil),            // 6: paloma.extension.v1.Action
	(*RunActionRequest)(nil),  // 7: paloma.extension.v1.RunActionRequest
	(*RunActionResponse)(nil), // 8: paloma.extension.v1.RunActionResponse
	(*Hide)(nil),              // 9: paloma.extension.v1.Hide
	(*Stay)(nil),              // 10: paloma.extension.v1.Stay
	(*Replace)(nil),           // 11: paloma.extension.v1.Replace
	(*ExtensionError)(nil),    // 12: paloma.extension.v1.ExtensionError
	(*ToolFacet)(nil),         // 13: paloma.extension.v1.ToolFacet
}
var file_schema_extension_capability_proto_depIdxs = []int32{
	1,  // 0: paloma.extension.v1.Capability.search:type_name -> paloma.extension.v1.SearchFacet
	13, // 1: paloma.extension.v1.Capability.tool:type_name -> paloma.extension.v1.ToolFacet
	5,  // 2: paloma.extension.v1.SearchResponse.items:type_name -> paloma.extension.v1.Item
	2,  // 3: paloma.extension.v1.Item.icon:type_name -> paloma.extension.v1.CapabilityIcon
	6,  // 4: paloma.extension.v1.Item.actions:type_name -> paloma.extension.v1.Action
	6,  // 5: paloma.extension.v1.RunActionRequest.action:type_name -> paloma.extension.v1.Action
	9,  // 6: paloma.extension.v1.RunActionResponse.hide:type_name -> paloma.extension.v1.Hide
	10, // 7: paloma.extension.v1.RunActionResponse.stay:type_name -> paloma.extension.v1.Stay
	11, // 8: paloma.extension.v1.RunActionResponse.replace:type_name -> paloma.extension.v1.Replace
	9,  // [9:9] is the sub-list for method output_type
	9,  // [9:9] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_schema_extension_capability_proto_init() }
func file_schema_extension_capability_proto_init() {
	if File_schema_extension_capability_proto != nil {
		return
	}
	file_schema_extension_tool_proto_init()
	file_schema_extension_capability_proto_msgTypes[0].OneofWrappers = []any{}
	file_schema_extension_capability_proto_msgTypes[2].OneofWrappers = []any{
		(*CapabilityIcon_Name)(nil),
		(*CapabilityIcon_Path)(nil),
		(*CapabilityIcon_Embedded)(nil),
	}
	file_schema_extension_capability_proto_msgTypes[5].OneofWrappers = []any{}
	file_schema_extension_capability_proto_msgTypes[8].OneofWrappers = []any{
		(*RunActionResponse_Hide)(nil),
		(*RunActionResponse_Stay)(nil),
		(*RunActionResponse_Replace)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_schema_extension_capability_proto_rawDesc), len(file_schema_extension_capability_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_schema_extension_capability_proto_goTypes,
		DependencyIndexes: file_schema_extension_capability_proto_depIdxs,
		MessageInfos:      file_schema_extension_capability_proto_msgTypes,
	}.Build()
	File_schema_extension_capability_proto = out.File
	file_schema_extension_capability_proto_goTypes = nil
	file_schema_extension_capability_proto_depIdxs = nil
}
