// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: schema/extension/main.proto

package extensionv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestEvent struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	EventId      uint64                 `protobuf:"varint,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	CapabilityId *string                `protobuf:"bytes,2,opt,name=capability_id,json=capabilityId,proto3,oneof" json:"capability_id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*RequestEvent_HandshakeRequest
	//	*RequestEvent_SearchRequest
	//	*RequestEvent_RunActionRequest
	//	*RequestEvent_InvokeToolRequest
	//	*RequestEvent_CancelToolRequest
	Payload       isRequestEvent_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestEvent) Reset() {
	*x = RequestEvent{}
	mi := &file_schema_extension_main_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestEvent) ProtoMessage() {}

func (x *RequestEvent) ProtoReflect() protoreflect.Message {
	mi := &file_schema_extension_main_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestEvent.ProtoReflect.Descriptor instead.
func (*RequestEvent) Descriptor() ([]byte, []int) {
	return file_schema_extension_main_proto_rawDescGZIP(), []int{0}
}

func (x *RequestEvent) GetEventId() uint64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *RequestEvent) GetCapabilityId() string {
	if x != nil && x.CapabilityId != nil {
		return *x.CapabilityId
	}
	return ""
}

func (x *RequestEvent) GetPayload() isRequestEvent_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *RequestEvent) GetHandshakeRequest() *HandshakeRequest {
	if x != nil {
		if x, ok := x.Payload.(*RequestEvent_HandshakeRequest); ok {
			return x.HandshakeRequest
		}
	}
	return nil
}

func (x *RequestEvent) GetSearchRequest() *SearchRequest {
	if x != nil {
		if x, ok := x.Payload.(*RequestEvent_SearchRequest); ok {
			return x.SearchRequest
		}
	}
	return nil
}

func (x *RequestEvent) GetRunActionRequest() *RunActionRequest {
	if x != nil {
		if x, ok := x.Payload.(*RequestEvent_RunActionRequest); ok {
			return x.RunActionRequest
		}
	}
	return nil
}

func (x *RequestEvent) GetInvokeToolRequest() *InvokeToolRequest {
	if x != nil {
		if x, ok := x.Payload.(*RequestEvent_InvokeToolRequest); ok {
			return x.InvokeToolRequest
		}
	}
	return nil
}

func (x *RequestEvent) GetCancelToolRequest() *CancelToolRequest {
	if x != nil {
		if x, ok := x.Payload.(*RequestEvent_CancelToolRequest); ok {
			return x.CancelToolRequest
		}
	}
	return nil
}

type isRequestEvent_Payload interface {
	isRequestEvent_Payload()
}

type RequestEvent_HandshakeRequest struct {
	HandshakeRequest *HandshakeRequest `protobuf:"bytes,3,opt,name=handshake_request,json=handshakeRequest,proto3,oneof"`
}

type RequestEvent_SearchRequest struct {
	SearchRequest *SearchRequest `protobuf:"bytes,4,opt,name=search_request,json=searchRequest,proto3,oneof"`
}

type RequestEvent_RunActionRequest struct {
	RunActionRequest *RunActionRequest `protobuf:"bytes,5,opt,name=run_action_request,json=runActionRequest,proto3,oneof"`
}

type RequestEvent_InvokeToolRequest struct {
	InvokeToolRequest *InvokeToolRequest `protobuf:"bytes,6,opt,name=invoke_tool_request,json=invokeToolRequest,proto3,oneof"`
}

type RequestEvent_CancelToolRequest struct {
	CancelToolRequest *CancelToolRequest `protobuf:"bytes,7,opt,name=cancel_tool_request,json=cancelToolRequest,proto3,oneof"`
}

func (*RequestEvent_HandshakeRequest) isRequestEvent_Payload() {}

func (*RequestEvent_SearchRequest) isRequestEvent_Payload() {}

func (*RequestEvent_RunActionRequest) isRequestEvent_Payload() {}

func (*RequestEvent_InvokeToolRequest) isRequestEvent_Payload() {}

func (*RequestEvent_CancelToolRequest) isRequestEvent_Payload() {}

type ResponseEvent struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	EventId uint64                 `protobuf:"varint,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ResponseEvent_HandshakeResponse
	//	*ResponseEvent_SearchResponse
	//	*ResponseEvent_RunActionResponse
	//	*ResponseEvent_InvokeToolResponse
	//	*ResponseEvent_CancelToolResponse
	//	*ResponseEvent_ExtensionError
	Payload       isResponseEvent_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseEvent) Reset() {
	*x = ResponseEvent{}
	mi := &file_schema_extension_main_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseEvent) ProtoMessage() {}

func (x *ResponseEvent) ProtoReflect() protoreflect.Message {
	mi := &file_schema_extension_main_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseEvent.ProtoReflect.Descriptor instead.
func (*ResponseEvent) Descriptor() ([]byte, []int) {
	return file_schema_extension_main_proto_rawDescGZIP(), []int{1}
}

func (x *ResponseEvent) GetEventId() uint64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *ResponseEvent) GetPayload() isResponseEvent_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ResponseEvent) GetHandshakeResponse() *HandshakeResponse {
	if x != nil {
		if x, ok := x.Payload.(*ResponseEvent_HandshakeResponse); ok {
			return x.HandshakeResponse
		}
	}
	return nil
}

func (x *ResponseEvent) GetSearchResponse() *SearchResponse {
	if x != nil {
		if x, ok := x.Payload.(*ResponseEvent_SearchResponse); ok {
			return x.SearchResponse
		}
	}
	return nil
}

func (x *ResponseEvent) GetRunActionResponse() *RunActionResponse {
	if x != nil {
		if x, ok := x.Payload.(*ResponseEvent_RunActionResponse); ok {
			return x.RunActionResponse
		}
	}
	return nil
}

func (x *ResponseEvent) GetInvokeToolResponse() *InvokeToolResponse {
	if x != nil {
		if x, ok := x.Payload.(*ResponseEvent_InvokeToolResponse); ok {
			return x.InvokeToolResponse
		}
	}
	return nil
}

func (x *ResponseEvent) GetCancelToolResponse() *CancelToolResponse {
	if x != nil {
		if x, ok := x.Payload.(*ResponseEvent_CancelToolResponse); ok {
			return x.CancelToolResponse
		}
	}
	return nil
}

func (x *ResponseEvent) GetExtensionError() *ExtensionError {
	if x != nil {
		if x, ok := x.Payload.(*ResponseEvent_ExtensionError); ok {
			return x.ExtensionError
		}
	}
	return nil
}

type isResponseEvent_Payload interface {
	isResponseEvent_Payload()
}

type ResponseEvent_HandshakeResponse struct {
	HandshakeResponse *HandshakeResponse `protobuf:"bytes,2,opt,name=handshake_response,json=handshakeResponse,proto3,oneof"`
}

type ResponseEvent_SearchResponse struct {
	SearchResponse *SearchResponse `protobuf:"bytes,3,opt,name=search_response,json=searchResponse,proto3,oneof"`
}

type ResponseEvent_RunActionResponse struct {
	RunActionResponse *RunActionResponse `protobuf:"bytes,4,opt,name=run_action_response,json=runActionResponse,proto3,oneof"`
}

type ResponseEvent_InvokeToolResponse struct {
	InvokeToolResponse *InvokeToolResponse `protobuf:"bytes,5,opt,name=invoke_tool_response,json=invokeToolResponse,proto3,oneof"`
}

type ResponseEvent_CancelToolResponse struct {
	CancelToolResponse *CancelToolResponse `protobuf:"bytes,6,opt,name=cancel_tool_response,json=cancelToolResponse,proto3,oneof"`
}

type ResponseEvent_ExtensionError struct {
	// all unary request errors populate through this response
	ExtensionError *ExtensionError `protobuf:"bytes,7,opt,name=extension_error,json=extensionError,proto3,oneof"`
}

func (*ResponseEvent_HandshakeResponse) isResponseEvent_Payload() {}

func (*ResponseEvent_SearchResponse) isResponseEvent_Payload() {}

func (*ResponseEvent_RunActionResponse) isResponseEvent_Payload() {}

func (*ResponseEvent_InvokeToolResponse) isResponseEvent_Payload() {}

func (*ResponseEvent_CancelToolResponse) isResponseEvent_Payload() {}

func (*ResponseEvent_ExtensionError) isResponseEvent_Payload() {}

type HandshakeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandshakeRequest) Reset() {
	*x = HandshakeRequest{}
	mi := &file_schema_extension_main_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeRequest) ProtoMessage() {}

func (x *HandshakeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_schema_extension_main_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeRequest.ProtoReflect.Descriptor instead.
func (*HandshakeRequest) Descriptor() ([]byte, []int) {
	return file_schema_extension_main_proto_rawDescGZIP(), []int{2}
}

type HandshakeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       uint64                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	ExtensionId   string                 `protobuf:"bytes,2,opt,name=extension_id,json=extensionId,proto3" json:"extension_id,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Author        *string                `protobuf:"bytes,4,opt,name=author,proto3,oneof" json:"author,omitempty"`
	Homepage      *string                `protobuf:"bytes,5,opt,name=homepage,proto3,oneof" json:"homepage,omitempty"`
	Capabilities  []*Capability          `protobuf:"bytes,6,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandshakeResponse) Reset() {
	*x = HandshakeResponse{}
	mi := &file_schema_extension_main_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeResponse) ProtoMessage() {}

func (x *HandshakeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_schema_extension_main_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeResponse.ProtoReflect.Descriptor instead.
func (*HandshakeResponse) Descriptor() ([]byte, []int) {
	return file_schema_extension_main_proto_rawDescGZIP(), []int{3}
}

func (x *HandshakeResponse) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *HandshakeResponse) GetExtensionId() string {
	if x != nil {
		return x.ExtensionId
	}
	return ""
}

func (x *HandshakeResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *HandshakeResponse) GetAuthor() string {
	if x != nil && x.Author != nil {
		return *x.Author
	}
	return ""
}

func (x *HandshakeResponse) GetHomepage() string {
	if x != nil && x.Homepage != nil {
		return *x.Homepage
	}
	return ""
}

func (x *HandshakeResponse) GetCapabilities() []*Capability {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

var File_schema_extension_main_proto protoreflect.FileDescriptor

const file_schema_extension_main_proto_rawDesc = "" +
	"\n" +
	"\x1bschema/extension/main.proto\x12\x13paloma.extension.v1\x1a!schema/extension/capability.proto\x1a\x1bschema/extension/tool.proto\"\x9e\x04\n" +
	"\fRequestEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\x04R\aeventId\x12(\n" +
	"\rcapability_id\x18\x02 \x01(\tH\x01R\fcapabilityId\x88\x01\x01\x12T\n" +
	"\x11handshake_request\x18\x03 \x01(\v2%.paloma.extension.v1.HandshakeRequestH\x00R\x10handshakeRequest\x12K\n" +
	"\x0esearch_request\x18\x04 \x01(\v2\".paloma.extension.v1.SearchRequestH\x00R\rsearchRequest\x12U\n" +
	"\x12run_action_request\x18\x05 \x01(\v2%.paloma.extension.v1.RunActionRequestH\x00R\x10runActionRequest\x12X\n" +
	"\x13invoke_tool_request\x18\x06 \x01(\v2&.paloma.extension.v1.InvokeToolRequestH\x00R\x11invokeToolRequest\x12X\n" +
	"\x13cancel_tool_request\x18\a \x01(\v2&.paloma.extension.v1.CancelToolRequestH\x00R\x11cancelToolRequestB\t\n" +
	"\apayloadB\x10\n" +
	"\x0e_capability_id\"\xc2\x04\n" +
	"\rResponseEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\x04R\aeventId\x12W\n" +
	"\x12handshake_response\x18\x02 \x01(\v2&.paloma.extension.v1.HandshakeResponseH\x00R\x11handshakeResponse\x12N\n" +
	"\x0fsearch_response\x18\x03 \x01(\v2#.paloma.extension.v1.SearchResponseH\x00R\x0esearchResponse\x12X\n" +
	"\x13run_action_response\x18\x04 \x01(\v2&.paloma.extension.v1.RunActionResponseH\x00R\x11runActionResponse\x12[\n" +
	"\x14invoke_tool_response\x18\x05 \x01(\v2'.paloma.extension.v1.InvokeToolResponseH\x00R\x12invokeToolResponse\x12[\n" +
	"\x14cancel_tool_response\x18\x06 \x01(\v2'.paloma.extension.v1.CancelToolResponseH\x00R\x12cancelToolResponse\x12N\n" +
	"\x0fextension_error\x18\a \x01(\v2#.paloma.extension.v1.ExtensionErrorH\x00R\x0eextensionErrorB\t\n" +
	"\apayload\"\x12\n" +
	"\x10HandshakeRequest\"\x8d\x02\n" +
	"\x11HandshakeResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x04R\aversion\x12!\n" +
	"\fextension_id\x18\x02 \x01(\tR\vextensionId\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1b\n" +
	"\x06author\x18\x04 \x01(\tH\x00R\x06author\x88\x01\x01\x12\x1f\n" +
	"\bhomepage\x18\x05 \x01(\tH\x01R\bhomepage\x88\x01\x01\x12C\n" +
	"\fcapabilities\x18\x06 \x03(\v2\x1f.paloma.extension.v1.CapabilityR\fcapabilitiesB\t\n" +
	"\a_authorB\v\n" +
	"\t_homepageB\xd7\x01\n" +
	"\x17com.paloma.extension.v1B\tMainProtoP\x01ZCpaloma/extensions/webfetch/internal/pb/schema/extension;extensionv1\xa2\x02\x03PEX\xaa\x02\x13Paloma.Extension.V1\xca\x02\x13Paloma\\Extension\\V1\xe2\x02\x1fPaloma\\Extension\\V1\\GPBMetadata\xea\x02\x15Paloma::Extension::V1b\x06proto3"

var (
	file_schema_extension_main_proto_rawDescOnce sync.Once
	file_schema_extension_main_proto_rawDescData []byte
)

func file_schema_extension_main_proto_rawDescGZIP() []byte {
	file_schema_extension_main_proto_rawDescOnce.Do(func() {
		file_schema_extension_main_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_schema_extension_main_proto_rawDesc), len(file_schema_extension_main_proto_rawDesc)))
	})
	return file_schema_extension_main_proto_rawDescData
}

var file_schema_extension_main_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_schema_extension_main_proto_goTypes = []any{
	(*RequestEvent)(nil),       // 0: paloma.extension.v1.RequestEvent
	(*ResponseEvent)(nil),      // 1: paloma.extension.v1.ResponseEvent
	(*HandshakeRequest)(nil),   // 2: paloma.extension.v1.HandshakeRequest
	(*HandshakeResponse)(nil),  // 3: paloma.extension.v1.HandshakeResponse
	(*SearchRequest)(nil),      // 4: paloma.extension.v1.SearchRequest
	(*RunActionRequest)(nil),   // 5: paloma.extension.v1.RunActionRequest
	(*InvokeToolRequest)(nil),  // 6: paloma.extension.v1.InvokeToolRequest
	(*CancelToolRequest)(nil),  // 7: paloma.extension.v1.CancelToolRequest
	(*SearchResponse)(nil),     // 8: paloma.extension.v1.SearchResponse
	(*RunActionResponse)(nil),  // 9: paloma.extension.v1.RunActionResponse
	(*InvokeToolResponse)(nil), // 10: paloma.extension.v1.InvokeToolResponse
	(*CancelToolResponse)(nil), // 11: paloma.extension.v1.CancelToolResponse
	(*ExtensionError)(nil),     // 12: paloma.extension.v1.ExtensionError
	(*Capability)(nil),         // 13: paloma.extension.v1.Capability
}
var file_schema_extension_main_proto_depIdxs = []int32{
	2,  // 0: paloma.extension.v1.RequestEvent.handshake_request:type_name -> paloma.extension.v1.HandshakeRequest
	4,  // 1: paloma.extension.v1.RequestEvent.search_request:type_name -> paloma.extension.v1.SearchRequest
	5,  // 2: paloma.extension.v1.RequestEvent.run_action_request:type_name -> paloma.extension.v1.RunActionRequest
	6,  // 3: paloma.extension.v1.RequestEvent.invoke_tool_request:type_name -> paloma.extension.v1.InvokeToolRequest
	7,  // 4: paloma.extension.v1.RequestEvent.cancel_tool_request:type_name -> paloma.extension.v1.CancelToolRequest
	3,  // 5: paloma.extension.v1.ResponseEvent.handshake_response:type_name -> paloma.extension.v1.HandshakeResponse
	8,  // 6: paloma.extension.v1.ResponseEvent.search_response:type_name -> paloma.extension.v1.SearchResponse
	9,  // 7: paloma.extension.v1.ResponseEvent.run_action_response:type_name -> paloma.extension.v1.RunActionResponse
	10, // 8: paloma.extension.v1.ResponseEvent.invoke_tool_response:type_name -> paloma.extension.v1.InvokeToolResponse
	11, // 9: paloma.extension.v1.ResponseEvent.cancel_tool_response:type_name -> paloma.extension.v1.CancelToolResponse
	12, // 10: paloma.extension.v1.ResponseEvent.extension_error:type_name -> paloma.extension.v1.ExtensionError
	13, // 11: paloma.extension.v1.HandshakeResponse.capabilities:type_name -> paloma.extension.v1.Capability
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_schema_extension_main_proto_init() }
func file_schema_extension_main_proto_init() {
	if File_schema_extension_main_proto != nil {
		return
	}
	file_schema_extension_capability_proto_init()
	file_schema_extension_tool_proto_init()
	file_schema_extension_main_proto_msgTypes[0].OneofWrappers = []any{
		(*RequestEvent_HandshakeRequest)(nil),
		(*RequestEvent_SearchRequest)(nil),
		(*RequestEvent_RunActionRequest)(nil),
		(*RequestEvent_InvokeToolRequest)(nil),
		(*RequestEvent_CancelToolRequest)(nil),
	}
	file_schema_extension_main_proto_msgTypes[1].OneofWrappers = []any{
		(*ResponseEvent_HandshakeResponse)(nil),
		(*ResponseEvent_SearchResponse)(nil),
		(*ResponseEvent_RunActionResponse)(nil),
		(*ResponseEvent_InvokeToolResponse)(nil),
		(*ResponseEvent_CancelToolResponse)(nil),
		(*ResponseEvent_ExtensionError)(nil),
	}
	file_schema_extension_main_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_schema_extension_main_proto_rawDesc), len(file_schema_extension_main_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_schema_extension_main_proto_goTypes,
		DependencyIndexes: file_schema_extension_main_proto_depIdxs,
		MessageInfos:      file_schema_extension_main_proto_msgTypes,
	}.Build()
	File_schema_extension_main_proto = out.File
	file_schema_extension_main_proto_goTypes = nil
	file_schema_extension_main_proto_depIdxs = nil
}
