// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: schema/extension/tool.proto

package extensionv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ToolFacet struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Description string                 `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	// json schema string for tools
	Parameters    string `protobuf:"bytes,2,opt,name=parameters,proto3" json:"parameters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolFacet) Reset() {
	*x = ToolFacet{}
	mi := &file_schema_extension_tool_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolFacet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolFacet) ProtoMessage() {}

func (x *ToolFacet) ProtoReflect() protoreflect.Message {
	mi := &file_schema_extension_tool_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolFacet.ProtoReflect.Descriptor instead.
func (*ToolFacet) Descriptor() ([]byte, []int) {
	return file_schema_extension_tool_proto_rawDescGZIP(), []int{0}
}

func (x *ToolFacet) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ToolFacet) GetParameters() string {
	if x != nil {
		return x.Parameters
	}
	return ""
}

type InvokeToolRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SessionId string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// id from llm tool_call payload
	CallId string `protobuf:"bytes,2,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	// tool arguments encoded as json
	Arguments     string `protobuf:"bytes,3,opt,name=arguments,proto3" json:"arguments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeToolRequest) Reset() {
	*x = InvokeToolRequest{}
	mi := &file_schema_extension_tool_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeToolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeToolRequest) ProtoMessage() {}

func (x *InvokeToolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_schema_extension_tool_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeToolRequest.ProtoReflect.Descriptor instead.
func (*InvokeToolRequest) Descriptor() ([]byte, []int) {
	return file_schema_extension_tool_proto_rawDescGZIP(), []int{1}
}

func (x *InvokeToolRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *InvokeToolRequest) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *InvokeToolRequest) GetArguments() string {
	if x != nil {
		return x.Arguments
	}
	return ""
}

type InvokeToolResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       *ToolContent           `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeToolResponse) Reset() {
	*x = InvokeToolResponse{}
	mi := &file_schema_extension_tool_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeToolResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeToolResponse) ProtoMessage() {}

func (x *InvokeToolResponse) ProtoReflect() protoreflect.Message {
	mi := &file_schema_extension_tool_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeToolResponse.ProtoReflect.Descriptor instead.
func (*InvokeToolResponse) Descriptor() ([]byte, []int) {
	return file_schema_extension_tool_proto_rawDescGZIP(), []int{2}
}

func (x *InvokeToolResponse) GetContent() *ToolContent {
	if x != nil {
		return x.Content
	}
	return nil
}

type ToolContent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// unique tag represent what current content represent.
	Tag        string       `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	Attributes []*Attribute `protobuf:"bytes,2,rep,name=attributes,proto3" json:"attributes,omitempty"`
	// Types that are valid to be assigned to Body:
	//
	//	*ToolContent_Text
	//	*ToolContent_Binary
	//	*ToolContent_Children
	Body          isToolContent_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolContent) Reset() {
	*x = ToolContent{}
	mi := &file_schema_extension_tool_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolContent) ProtoMessage() {}

func (x *ToolContent) ProtoReflect() protoreflect.Message {
	mi := &file_schema_extension_tool_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolContent.ProtoReflect.Descriptor instead.
func (*ToolContent) Descriptor() ([]byte, []int) {
	return file_schema_extension_tool_proto_rawDescGZIP(), []int{3}
}

func (x *ToolContent) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *ToolContent) GetAttributes() []*Attribute {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *ToolContent) GetBody() isToolContent_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *ToolContent) GetText() string {
	if x != nil {
		if x, ok := x.Body.(*ToolContent_Text); ok {
			return x.Text
		}
	}
	return ""
}

func (x *ToolContent) GetBinary() *Binary {
	if x != nil {
		if x, ok := x.Body.(*ToolContent_Binary); ok {
			return x.Binary
		}
	}
	return nil
}

func (x *ToolContent) GetChildren() *Children {
	if x != nil {
		if x, ok := x.Body.(*ToolContent_Children); ok {
			return x.Children
		}
	}
	return nil
}

type isToolContent_Body interface {
	isToolContent_Body()
}

type ToolContent_Text struct {
	Text string `protobuf:"bytes,3,opt,name=text,proto3,oneof"`
}

type ToolContent_Binary struct {
	Binary *Binary `protobuf:"bytes,4,opt,name=binary,proto3,oneof"`
}

type ToolContent_Children struct {
	Children *Children `protobuf:"bytes,5,opt,name=children,proto3,oneof"`
}

func (*ToolContent_Text) isToolContent_Body() {}

func (*ToolContent_Binary) isToolContent_Body() {}

func (*ToolContent_Children) isToolContent_Body() {}

type Children struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*ToolContent         `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Children) Reset() {
	*x = Children{}
	mi := &file_schema_extension_tool_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Children) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Children) ProtoMessage() {}

func (x *Children) ProtoReflect() protoreflect.Message {
	mi := &file_schema_extension_tool_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Children.ProtoReflect.Descriptor instead.
func (*Children) Descriptor() ([]byte, []int) {
	return file_schema_extension_tool_proto_rawDescGZIP(), []int{4}
}

func (x *Children) GetNodes() []*ToolContent {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type Attribute struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Attribute) Reset() {
	*x = Attribute{}
	mi := &file_schema_extension_tool_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Attribute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attribute) ProtoMessage() {}

func (x *Attribute) ProtoReflect() protoreflect.Message {
	mi := &file_schema_extension_tool_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attribute.ProtoReflect.Descriptor instead.
func (*Attribute) Descriptor() ([]byte, []int) {
	return file_schema_extension_tool_proto_rawDescGZIP(), []int{5}
}

func (x *Attribute) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Attribute) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type Binary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MimeType      string                 `protobuf:"bytes,1,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Binary) Reset() {
	*x = Binary{}
	mi := &file_schema_extension_tool_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Binary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Binary) ProtoMessage() {}

func (x *Binary) ProtoReflect() protoreflect.Message {
	mi := &file_schema_extension_tool_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Binary.ProtoReflect.Descriptor instead.
func (*Binary) Descriptor() ([]byte, []int) {
	return file_schema_extension_tool_proto_rawDescGZIP(), []int{6}
}

func (x *Binary) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *Binary) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type CancelToolRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelToolRequest) Reset() {
	*x = CancelToolRequest{}
	mi := &file_schema_extension_tool_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelToolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelToolRequest) ProtoMessage() {}

func (x *CancelToolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_schema_extension_tool_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelToolRequest.ProtoReflect.Descriptor instead.
func (*CancelToolRequest) Descriptor() ([]byte, []int) {
	return file_schema_extension_tool_proto_rawDescGZIP(), []int{7}
}

func (x *CancelToolRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type CancelToolResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelToolResponse) Reset() {
	*x = CancelToolResponse{}
	mi := &file_schema_extension_tool_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelToolResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelToolResponse) ProtoMessage() {}

func (x *CancelToolResponse) ProtoReflect() protoreflect.Message {
	mi := &file_schema_extension_tool_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelToolResponse.ProtoReflect.Descriptor instead.
func (*CancelToolResponse) Descriptor() ([]byte, []int) {
	return file_schema_extension_tool_proto_rawDescGZIP(), []int{8}
}

var File_schema_extension_tool_proto protoreflect.FileDescriptor

const file_schema_extension_tool_proto_rawDesc = "" +
	"\n" +
	"\x1bschema/extension/tool.proto\x12\x13paloma.extension.v1\"M\n" +
	"\tToolFacet\x12 \n" +
	"\vdescription\x18\x01 \x01(\tR\vdescription\x12\x1e\n" +
	"\n" +
	"parameters\x18\x02 \x01(\tR\n" +
	"parameters\"i\n" +
	"\x11InvokeToolRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\acall_id\x18\x02 \x01(\tR\x06callId\x12\x1c\n" +
	"\targuments\x18\x03 \x01(\tR\targuments\"P\n" +
	"\x12InvokeToolResponse\x12:\n" +
	"\acontent\x18\x01 \x01(\v2 .paloma.extension.v1.ToolContentR\acontent\"\xf1\x01\n" +
	"\vToolContent\x12\x10\n" +
	"\x03tag\x18\x01 \x01(\tR\x03tag\x12>\n" +
	"\n" +
	"attributes\x18\x02 \x03(\v2\x1e.paloma.extension.v1.AttributeR\n" +
	"attributes\x12\x14\n" +
	"\x04text\x18\x03 \x01(\tH\x00R\x04text\x125\n" +
	"\x06binary\x18\x04 \x01(\v2\x1b.paloma.extension.v1.BinaryH\x00R\x06binary\x12;\n" +
	"\bchildren\x18\x05 \x01(\v2\x1d.paloma.extension.v1.ChildrenH\x00R\bchildrenB\x06\n" +
	"\x04body\"B\n" +
	"\bChildren\x126\n" +
	"\x05nodes\x18\x01 \x03(\v2 .paloma.extension.v1.ToolContentR\x05nodes\"3\n" +
	"\tAttribute\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"9\n" +
	"\x06Binary\x12\x1b\n" +
	"\tmime_type\x18\x01 \x01(\tR\bmimeType\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"2\n" +
	"\x11CancelToolRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\x14\n" +
	"\x12CancelToolResponseB\xd7\x01\n" +
	"\x17com.paloma.extension.v1B\tToolProtoP\x01ZCpaloma/extensions/webfetch/internal/pb/schema/extension;extensionv1\xa2\x02\x03PEX\xaa\x02\x13Paloma.Extension.V1\xca\x02\x13Paloma\\Extension\\V1\xe2\x02\x1fPaloma\\Extension\\V1\\GPBMetadata\xea\x02\x15Paloma::Extension::V1b\x06proto3"

var (
	file_schema_extension_tool_proto_rawDescOnce sync.Once
	file_schema_extension_tool_proto_rawDescData []byte
)

func file_schema_extension_tool_proto_rawDescGZIP() []byte {
	file_schema_extension_tool_proto_rawDescOnce.Do(func() {
		file_schema_extension_tool_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_schema_extension_tool_proto_rawDesc), len(file_schema_extension_tool_proto_rawDesc)))
	})
	return file_schema_extension_tool_proto_rawDescData
}

var file_schema_extension_tool_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_schema_extension_tool_proto_goTypes = []any{
	(*ToolFacet)(nil),          // 0: paloma.extension.v1.ToolFacet
	(*InvokeToolRequest)(nil),  // 1: paloma.extension.v1.InvokeToolRequest
	(*InvokeToolResponse)(nil), // 2: paloma.extension.v1.InvokeToolResponse
	(*ToolContent)(nil),        // 3: paloma.extension.v1.ToolContent
	(*Children)(nil),           // 4: paloma.extension.v1.Children
	(*Attribute)(nil),          // 5: paloma.extension.v1.Attribute
	(*Binary)(nil),             // 6: paloma.extension.v1.Binary
	(*CancelToolRequest)(nil),  // 7: paloma.extension.v1.CancelToolRequest
	(*CancelToolResponse)(nil), // 8: paloma.extension.v1.CancelToolResponse
}
var file_schema_extension_tool_proto_depIdxs = []int32{
	3, // 0: paloma.extension.v1.InvokeToolResponse.content:type_name -> paloma.extension.v1.ToolContent
	5, // 1: paloma.extension.v1.ToolContent.attributes:type_name -> paloma.extension.v1.Attribute
	6, // 2: paloma.extension.v1.ToolContent.binary:type_name -> paloma.extension.v1.Binary
	4, // 3: paloma.extension.v1.ToolContent.children:type_name -> paloma.extension.v1.Children
	3, // 4: paloma.extension.v1.Children.nodes:type_name -> paloma.extension.v1.ToolContent
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_schema_extension_tool_proto_init() }
func file_schema_extension_tool_proto_init() {
	if File_schema_extension_tool_proto != nil {
		return
	}
	file_schema_extension_tool_proto_msgTypes[3].OneofWrappers = []any{
		(*ToolContent_Text)(nil),
		(*ToolContent_Binary)(nil),
		(*ToolContent_Children)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_schema_extension_tool_proto_rawDesc), len(file_schema_extension_tool_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_schema_extension_tool_proto_goTypes,
		DependencyIndexes: file_schema_extension_tool_proto_depIdxs,
		MessageInfos:      file_schema_extension_tool_proto_msgTypes,
	}.Build()
	File_schema_extension_tool_proto = out.File
	file_schema_extension_tool_proto_goTypes = nil
	file_schema_extension_tool_proto_depIdxs = nil
}
