[package]
name = "scry-extension-base"
version = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
publish = false

[dependencies]
async-trait = { workspace = true }
dashmap = { workspace = true }
scry-extension-protocol = { workspace = true }
scry-utils = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt", "sync"] }
tokio-util = { workspace = true }
