[package]
name = "scry-extension-base"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
scry-extension-protocol = { workspace = true }
scry-utils = { workspace = true }
tokio = { workspace = true, features = ["rt", "sync"] }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt", "sync"] }
