[package]
name = "scry-controller"
version = "0.0.1"
edition.workspace = true
rust-version.workspace = true

[dependencies]
scry-capability = { path = "../scry-capability" }
scry-storage = { path = "../scry-storage" }
scry-provider = { path = "../scry-provider" }
tokio = { workspace = true, features = ["rt"] }
serde = { workspace = true }
dashmap = { workspace = true }
reqwest = { workspace = true }
thiserror = { workspace = true }
