use std::io;

use prost::{
    bytes::{Buf, BufMut, Bytes, BytesMut},
    encoding::{decode_varint, encode_varint, encoded_len_varint},
};
use tokio_util::codec::{Decoder, Encoder};
pub use tokio_util::codec::{FramedRead, FramedWrite};

/// Custom encoder and decoder to match the encode and decode format for official protobuf runtime.
/// This should be able to directly parsing protobuf generated by other language.
/// FORMAT: protobuf message length(varint bytes) + protobuf message bytes
#[derive(Debug, Default, Clone, Copy)]
pub struct VarintDelimitedCodec;

/// Max possible length for VARINT LENGTH
const MAX_VARINT_LENGTH: usize = 10;

fn invalid_data(error: impl Into<Box<dyn std::error::Error + Send + Sync>>) -> io::Error {
    io::Error::new(io::ErrorKind::InvalidData, error)
}

impl Decoder for VarintDelimitedCodec {
    type Item = BytesMut;
    type Error = io::Error;

    fn decode(&mut self, src: &mut BytesMut) -> io::Result<Option<BytesMut>> {
        let Some(prefix_end) = src
            .iter()
            .take(MAX_VARINT_LENGTH)
            .position(|byte| byte & 0x80 == 0)
        else {
            // when the buffer size is greater than the max possible size,
            // and we cannot find the breaking byte meaning this starting chunk is corrupted
            if src.len() >= MAX_VARINT_LENGTH {
                return Err(invalid_data("length prefix is not a valid varint"));
            }
            // continue on not enough bytes
            return Ok(None);
        };

        // slice and parse the message length
        let mut prefix = &src[..=prefix_end];
        let length = decode_varint(&mut prefix).map_err(invalid_data)?;
        let length = usize::try_from(length)
            .map_err(|_| invalid_data(format!("payload length {length} exceeds usize")))?;
        let prefix_length = prefix_end + 1; // index + 1 = length
        let total_message_size = length.checked_add(prefix_length).ok_or_else(|| {
            invalid_data(format!(
                "frame length {length} + {prefix_length} overflows usize"
            ))
        })?;

        // the frame buffer does not contain the total message payload yet
        // proactively ask frame buffer to relocate to fit the rest of the message size if needed
        if src.len() < total_message_size {
            src.reserve(total_message_size - src.len());
            return Ok(None);
        }

        src.advance(prefix_length);
        Ok(Some(src.split_to(length)))
    }
}

impl Encoder<Bytes> for VarintDelimitedCodec {
    type Error = io::Error;

    fn encode(&mut self, payload: Bytes, dst: &mut BytesMut) -> io::Result<()> {
        dst.reserve(encoded_len_varint(payload.len() as u64) + payload.len());
        encode_varint(payload.len() as u64, dst);
        dst.put(payload);
        Ok(())
    }
}
