[package]
name = "paloma-provider-base"
version = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
license = "Apache-2.0"
publish = false

[dependencies]
async-trait = { workspace = true }
dashmap = { workspace = true }
log = { workspace = true }
paloma-provider-protocol = { workspace = true }
paloma-utils = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["rt", "sync"] }
tokio-util = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt", "test-util", "time"] }

[lints]
workspace = true
