[package]
name = "scry-utils"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
backon = { workspace = true }
prost = "0.14.4"
tokio-util = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt", "test-util", "time"] }
