[package]
name = "paloma-utils"
version = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
license = "Apache-2.0"
publish = false

[dependencies]
backon = { workspace = true }
env_logger = { workspace = true }
futures = { workspace = true }
log = { workspace = true }
prost = { workspace = true }
tokio = { workspace = true, features = ["io-std", "rt", "sync"] }
tokio-util = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt", "test-util", "time"] }

[lints]
workspace = true
