syntax = "proto3";

package paloma.extension.v1;

import "schema/extension/tool.proto";

message Capability {
  string capability_id = 1;
  string description = 2;

  optional SearchFacet search = 3;
  optional ToolFacet tool = 4;
}

// placeholder to indicate capability has search support
message SearchFacet {}

message CapabilityIcon {
  oneof icon {
    string name = 1;
    string path = 2;
    bytes embedded = 3;
  }
}

message SearchRequest {
  string input = 1;
}

message SearchResponse {
  repeated Item items = 1;
}

message Item {
  string title = 1;
  optional string subtitle = 2;
  optional CapabilityIcon icon = 3;
  repeated Action actions = 4;
}

message Action {
  // action name for both UI display and as action enum
  string label = 1;
  // action input params
  repeated string params = 2;
  // whether the action is the default action
  bool primary = 3;
}

message RunActionRequest {
  Action action = 1;
}

message RunActionResponse {
  oneof behavior {
    Hide hide = 1;
    Stay stay = 2;
    Replace replace = 3;
  }
}

message Hide {}

message Stay {}

// replace the launcher input with the given text
message Replace {
  string input = 1;
}

// all unary request errors populate through this response
message ExtensionError {
  string error = 1;
}
