[package]
name = "scry-permission"
version = "0.0.1"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true
description = "Permission checker for Scry."

[dependencies]
tree-sitter = "0.26.9"
tree-sitter-bash = "0.25.1"
scry-storage = { path = "../scry-storage" }
thiserror = { workspace = true }
