syntax = "proto3";

package paloma.binding.v1;

import "schema/binding/common.proto";
import "schema/binding/session.proto";
import "schema/extension/capability.proto";

message QueryResponse {
  ExtensionCapabilityId extension_capability_id = 1;
  string name = 2;
  repeated paloma.extension.v1.Item items = 3;
}

message SearchRenderEvent {
  oneof payload {
    QueryResponse append = 1;
  }
}

message TextDelta {
  ProviderBackendId provider_backend_id = 1;
  string text = 2;
}

message ToolCall {
  string tool_name = 1;
  string arguments = 2;
  optional string description = 3;
  repeated UserDecision decisions = 4;
}

message ChatRenderEvent {
  oneof payload {
    string user_prompt = 1;
    TextDelta text_delta = 2;
    string reasoning_delta = 3;
    ToolCall tool_call = 4;
  }
}

message Cancel {}

message Done {}

message RenderEvent {
  oneof payload {
    SearchRenderEvent search = 1;
    ChatRenderEvent chat = 2;
    Cancel cancel = 3;
    Done done = 4;
    string error = 5;
  }
}
