[package]
name = "scry-storage"
version = "0.0.1"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true
description = "Storage primitives for Scry."

[dependencies]
sqlx = { version = "0.8.6", features = ["runtime-tokio", "sqlite"] }
thiserror = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["rt", "macros"] }
tempfile = "3"
