[package]
name = "scry-storage"
version = "0.0.1"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true
description = "Storage primitives for Scry."

[dependencies]
sqlx = { workspace = true }
tokio = { workspace = true, features = ["fs", "io-util", "sync", "rt"] }
thiserror = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["rt", "macros"] }
