[package]
name = "scry-provider-openai"
version = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
publish = false

[dependencies]
async-trait = { workspace = true }
base64 = { version = "0.22.1", default-features = false, features = ["std"] }
chrono = { workspace = true, features = ["serde"] }
eventsource-stream = { workspace = true }
futures = { workspace = true }
log = { workspace = true }
reqwest = { workspace = true }
scry-provider-base = { workspace = true }
scry-provider-protocol = { workspace = true }
scry-utils = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["io-std", "macros", "rt-multi-thread"] }
