[package]
name = "paloma-provider-openai"
version = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
publish = false

[dependencies]
async-trait = { workspace = true }
base64 = { version = "0.22.1", default-features = false, features = ["std"] }
chrono = { workspace = true, features = ["serde"] }
eventsource-stream = { workspace = true }
futures = { workspace = true }
log = { workspace = true }
paloma-provider-base = { workspace = true }
paloma-provider-protocol = { workspace = true }
paloma-utils = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["io-std", "macros", "rt-multi-thread"] }
